inventory/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    # Home
    path('', views.Index.as_view(), name='index'),
    path("login", include("django.contrib.auth.urls"), name="login"),
    path("logout", views.logout_view, name="logout"),
    # Ingredient Paths
    path('ingredient', views.IngredientView.as_view(), name='ingredient_list'),
    path('ingredient/create', views.IngredientCreateView.as_view(), name='ingredient_create'),
    path('ingredient/<pk>/update', views.IngredientUpdateView.as_view(), name='ingredient_update'),
    path('ingredient/<pk>/delete', views.IngredientDeleteView.as_view(), name='ingredient_delete'),
    path('ingredient/<tk>/requieriment', views.ingredient_requirement_view, name='ingredient_requirement_list'),
    # Menu Item Paths
    path('menu_item', views.MenuItemView.as_view(), name='menu_item_list'),
    path('menu_item/create', views.MenuItemCreateView.as_view(), name='menu_item_create'),
    path('menu_item/<pk>/update', views.MenuItemUpdateView.as_view(), name='menu_item_update'),
    path('menu_item/<pk>/delete', views.MenuItemDeleteView.as_view(), name='menu_item_delete'),
    # Recipe Requirement Paths
    path('menu_item/recipe_requirement/<tk>', views.recipe_requirement_view, name='recipe_requirement_list'),
    path('menu_item/recipe_requirement/<tk>/create', views.RecipeRequirementCreateView.as_view(),
         name='recipe_requirement_create'),
    path('menu_item/recipe_requirement/<tk>/<pk>/update', views.RecipeRequirementUpdateView.as_view(),
         name='recipe_requirement_update'),
    path('menu_item/recipe_requirement/<tk>/<pk>/delete', views.RecipeRequirementDeleteView.as_view(),
         name='recipe_requirement_delete'),
    # Purchase Paths
    path('purchase', views.PurchaseView.as_view(), name='purchase_list'),
    path('purchase/create', views.PurchaseCreateView.as_view(), name='purchase_create'),
    path('purchase/<pk>/delete', views.PurchaseDeleteView.as_view(), name='purchase_delete'),
]

inventory/models.py
from django.db import models
from django.urls import reverse


class Ingredient(models.Model):
    KILOGRAM = "kg"
    MILLILITER = "ml"
    LITER = "l"
    GRAM = "gr"
    PIECE = "p"
    METER = "m"
    CUP = "cup"
    OUNCE = "oz"
    UNIT = "u"
    POUND = "lb"
    UNIT_CHOICES = {
        KILOGRAM: "Kilogram",
        MILLILITER: "Milliliter",
        LITER: "Liter",
        GRAM: "Gram",
        PIECE: "Piece",
        METER: "Meter",
        CUP: "Cup",
        OUNCE: "Ounce",
        UNIT: "Unit",
        POUND: "Pound",
    }

    name = models.CharField(max_length=200)
    quantity = models.DecimalField(max_digits=12, decimal_places=2)
    unit = models.CharField(choices=UNIT_CHOICES, max_length=3, default=KILOGRAM)
    unit_price = models.DecimalField(max_digits=12, decimal_places=2)

    def __str__(self):
        return f'{self.name}'

    @staticmethod
    def get_absolute_url():
        return "/ingredient"

    def remove_quantity(self, quantity):
        self.quantity -= quantity
        self.save()


class MenuItem(models.Model):
    title = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=12, decimal_places=2)

    def __str__(self):
        return f'{self.title}'

    @staticmethod
    def get_absolute_url():
        return "/menu_item"

    def can_make_recipe(self):
        for recipe_requirement in self.recipe.all():
            if not recipe_requirement.there_are_ingredient():
                return False
        return True

    def make_recipe(self):
        for recipe_requirement in self.recipe.all():
            recipe_requirement.take_ingredient()

    def recipe_cost(self):
        cost = 0
        for recipe_requirement in self.recipe.all():
            cost += recipe_requirement.cost()
        return cost


class RecipeRequirement(models.Model):
    menu_item = models.ForeignKey(MenuItem, related_name='recipe', on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, related_name='recipe', on_delete=models.CASCADE)
    quantity = models.DecimalField(max_digits=12, decimal_places=2)

    def __str__(self):
        return f'{self.ingredient}, quantity: {self.quantity}'

    def get_absolute_url(self):
        return reverse('recipe_requirement', kwargs={'tk': self.menu_item})

    def there_are_ingredient(self):
        return True if self.ingredient.quantity >= self.quantity else False

    def take_ingredient(self):
        self.ingredient.remove_quantity(self.quantity)

    def cost(self):
        return self.ingredient.unit_price * self.quantity


class Purchase(models.Model):
    menu_item = models.ForeignKey(MenuItem, on_delete=models.CASCADE)
    revenue = models.DecimalField(max_digits=12, decimal_places=2)
    cost = models.DecimalField(max_digits=12, decimal_places=2)
    profit = models.DecimalField(max_digits=12, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True)

    @staticmethod
    def get_absolute_url():
        return "/purchase"

inventory/forms.py
from django import forms
from .models import Ingredient, MenuItem, RecipeRequirement, Purchase


class IngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = ['name', 'quantity', 'unit', 'unit_price']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingredient'}),
            'quantity': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Quantity', 'step': '0.01'}),
            'unit': forms.Select(attrs={'class': 'form-select'}),
            'unit_price': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Price', 'step': '0.01'}),
        }


class MenuItemForm(forms.ModelForm):
    class Meta:
        model = MenuItem
        fields = ['title', 'price']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Title'}),
            'price': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Price', 'step': '0.01'}),
        }


class RecipeRequirementForm(forms.ModelForm):
    ingredient = forms.ModelChoiceField(
        queryset=Ingredient.objects.all(),
        widget=forms.Select(attrs={'class': 'form-select'}),
    )

    class Meta:
        model = RecipeRequirement
        fields = ['ingredient', 'quantity']
        widgets = {
            'quantity': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Quantity', 'step': '0.01'}),
        }


class PurchaseForm(forms.ModelForm):
    class Meta:
        model = Purchase
        fields = ['menu_item']
        widgets = {
            'menu_item': forms.Select(attrs={'class': 'form-select'}),
        }

inventory/views.py
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Ingredient, MenuItem, RecipeRequirement, Purchase
from .forms import IngredientForm, MenuItemForm, RecipeRequirementForm, PurchaseForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout


# Home
def logout_view(request):
    logout(request)
    return redirect("index")


class Index(LoginRequiredMixin, TemplateView):
    template_name = 'inventory/index.html'


# Ingredient Views
class IngredientView(LoginRequiredMixin, ListView):
    model = Ingredient
    template_name = "inventory/ingredient.html"


class IngredientCreateView(LoginRequiredMixin, CreateView):
    model = Ingredient
    template_name = "inventory/add_ingredient.html"
    form_class = IngredientForm


class IngredientUpdateView(LoginRequiredMixin, UpdateView):
    model = Ingredient
    template_name = "inventory/update_ingredient.html"
    form_class = IngredientForm
    success_url = "/ingredient"


class IngredientDeleteView(LoginRequiredMixin, DeleteView):
    model = Ingredient
    template_name = "inventory/delete_ingredient.html"
    success_url = "/ingredient"


@login_required
def ingredient_requirement_view(request, tk):
    menu = MenuItem.objects.get(id=tk)
    recipe_requirements = menu.recipe.all()
    ingredients = [recipe_requirement.ingredient for recipe_requirement in recipe_requirements]
    requirement_ingredients = zip(ingredients, recipe_requirements)
    context = {
        'menu': menu,
        'requirement_ingredients': requirement_ingredients,
    }
    return render(request, "inventory/ingredient_requirement.html", context)


# Menu Item Views
class MenuItemView(LoginRequiredMixin, ListView):
    model = MenuItem
    template_name = "inventory/menu_item.html"


class MenuItemCreateView(LoginRequiredMixin, CreateView):
    model = MenuItem
    template_name = "inventory/add_menu_item.html"
    form_class = MenuItemForm


class MenuItemUpdateView(LoginRequiredMixin, UpdateView):
    model = MenuItem
    template_name = "inventory/update_menu_item.html"
    form_class = MenuItemForm
    success_url = "/menu_item"


class MenuItemDeleteView(LoginRequiredMixin, DeleteView):
    model = MenuItem
    template_name = "inventory/delete_menu_item.html"
    success_url = "/menu_item"


@login_required
def recipe_requirement_view(request, tk):
    menu = get_object_or_404(MenuItem, pk=tk)
    recipe_requirements = menu.recipe.all()
    context = {
        "menu": menu,
        "recipe_requirements": recipe_requirements,
    }
    return render(request, 'inventory/recipe_requirement.html', context)


class RecipeRequirementCreateView(LoginRequiredMixin, CreateView):
    model = RecipeRequirement
    template_name = 'inventory/add_recipe_requirement.html'
    form_class = RecipeRequirementForm

    def get_initial(self):
        tk = self.kwargs.get('tk')
        menu_item = MenuItem.objects.get(id=tk)
        initial = super().get_initial()
        initial['menu_item'] = menu_item
        return initial

    def get_context_data(self, **kwargs):
        contex = super().get_context_data(**kwargs)
        tk = self.kwargs.get('tk')
        contex['menu_item'] = MenuItem.objects.get(id=tk)
        return contex

    def get_success_url(self):
        tk = self.kwargs['tk']
        return reverse_lazy('recipe_requirement_list', kwargs={'tk': tk})

    def form_valid(self, form):
        menu_item = MenuItem.objects.get(id=self.kwargs['tk'])
        form.instance.menu_item = menu_item
        return super().form_valid(form)


class RecipeRequirementUpdateView(LoginRequiredMixin, UpdateView):
    model = RecipeRequirement
    template_name = 'inventory/update_recipe_requirement.html'
    form_class = RecipeRequirementForm

    def get_success_url(self):
        tk = self.kwargs['tk']
        return reverse_lazy('recipe_requirement_list', kwargs={'tk': tk})

    def form_valid(self, form):
        menu_item = MenuItem.objects.get(id=self.kwargs['tk'])
        form.instance.menu_item = menu_item
        return super().form_valid(form)


class RecipeRequirementDeleteView(LoginRequiredMixin, DeleteView):
    model = RecipeRequirement
    template_name = 'inventory/delete_recipe_requirement.html'

    def get_success_url(self):
        tk = self.kwargs['tk']
        return reverse_lazy('recipe_requirement_list', kwargs={'tk': tk})


class PurchaseView(LoginRequiredMixin, ListView):
    model = Purchase
    template_name = "inventory/purchase.html"


class PurchaseCreateView(LoginRequiredMixin, CreateView):
    model = Purchase
    template_name = "inventory/add_purchase.html"
    form_class = PurchaseForm

    def form_valid(self, form):
        menu_item = form.instance.menu_item
        if not menu_item.can_make_recipe():
            return HttpResponseRedirect(reverse_lazy('ingredient_requirement_list', kwargs={'tk': menu_item.id}))
        form.instance.revenue = menu_item.price
        form.instance.cost = round(menu_item.recipe_cost(), 2)
        form.instance.profit = round(menu_item.price - menu_item.recipe_cost(), 2)

        menu_item.make_recipe()
        return super().form_valid(form)


class PurchaseDeleteView(LoginRequiredMixin, DeleteView):
    model = Purchase
    template_name = "inventory/delete_purchase.html"
    success_url = "/purchase"

templates/inventory/add_ingredient.html
{% extends "inventory/base.html" %}
{% load static %}

{% block body %}
    <div class="d-flex align-items-center">
        <div class="border rounded">
            <form class="row g-3 needs-validation" method="post">
                {% csrf_token %}
                <div class="col-md-6">
                    <label for="id_name" class="form-label">Name</label>
                    {{ form.name }}
                    <div class="valid-feedback">
                        Looks good!
                    </div>
                </div>
                <div class="col-md-6">
                    <label for="id_quantity" class="form-label">Quantity</label>
                    {{ form.quantity }}
                    <div class="valid-feedback">
                        Looks good!
                    </div>
                </div>
                <div class="col-md-6">
                    <label for="id_unit" class="form-label">Unit</label>
                    {{ form.unit }}
                </div>
                <div class="col-md-6">
                    <label for="id_unit_price" class="form-label">Unit Price</label>
                    {{ form.unit_price }}
                    <div class="valid-feedback">
                        Looks good!
                    </div>
                </div>
                <div class="col-12">
                    <input class="btn btn-primary" type="submit" value="Submit" />
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/inventory/add_purchase.html
{% extends "inventory/base.html" %}
{% load static %}

{% block body %}
    <div class="d-flex align-items-center">
        <div class="border rounded">
            <form class="row g-3 needs-validation" method="post">
                {% csrf_token %}
                <div class="col-md-6">
                    <label for="id_menu_item" class="form-label">Menu Item</label>
                    {{ form.menu_item }}
                </div>
                <div class="col-12">
                    <input class="btn btn-primary" type="submit" value="Submit"/>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/inventory/add_recipe_requirement.html
{% extends "inventory/base.html" %}
{% load static %}

{% block body %}
    <h1> New Requirement for {{ menu_item.title }} recipe</h1>
    <div class="d-flex align-items-center">
        <div class="border rounded">
            <form class="row g-3 needs-validation" method="post">
                {% csrf_token %}
                <div class="col-md-6">
                    <label for="id_ingredient" class="form-label">Name</label>
                    {{ form.ingredient }}
                </div>
                <div class="col-md-6">
                    <label for="id_quantity" class="form-label">Quantity</label>
                    {{ form.quantity }}
                    <div class="valid-feedback">
                        Looks good!
                    </div>
                </div>
                <div class="col-12">
                    <input class="btn btn-primary" type="submit" value="Submit"/>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/inventory/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1" charset="UTF-8">
    <title>test</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body data-bs-theme="dark">
<h1><a href="{% url "index" %}">Inventory</a></h1>
<div class="btn-group" role="group" aria-label="Basic example">
  <a type="button" class="btn btn-primary" href="{% url "ingredient_list" %}">Ingredient</a>
  <a type="button" class="btn btn-primary" href="{% url "menu_item_list" %}">Menu Item</a>
  <a type="button" class="btn btn-secondary" href="{% url "purchase_list" %}">Purchase</a>
</div>
<a type="button" class="btn btn-primary" href="{% url "logout" %}">Logout</a>

{% block body %}
{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
</html>

templates/inventory/delete_menu_item.html
{% extends "inventory/base.html" %}
{% load static %}

{% block body %}
    <div class="d-flex align-items-center">
        <div class="border rounded">
            <form class="row g-3 needs-validation" method="post">
                {% csrf_token %}
                <div class="col-md-6">
                    <p>
                        are you sure you want to delete "{{ object }}"
                    </p>
                </div>
                <div class="col-12">
                    <input class="btn btn-primary" type="submit" value="Submit" />
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/inventory/delete_recipe_requirement.html
{% extends "inventory/base.html" %}
{% load static %}

{% block body %}
    <div class="d-flex align-items-center">
        <div class="border rounded">
            <form class="row g-3 needs-validation" method="post">
                {% csrf_token %}
                <div class="col-md-6">
                    <p>
                        are you sure you want to delete "{{ object }}"
                    </p>
                </div>
                <div class="col-12">
                    <input class="btn btn-primary" type="submit" value="Submit" />
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/inventory/index.html
{% extends "inventory/base.html" %}
{% load static %}

{% block body %}
{% endblock %}

templates/inventory/ingredient.html
{% extends "inventory/base.html" %}
{% load static %}

{% block body %}
    <div class="d-flex align-items-center">
        <div class="border rounded">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Unit</th>
                    <th scope="col">Unit Price</th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody class="table-group-divider">
                {% for ingredient in ingredient_list %}
                    <tr>
                        <th scope="row">1</th>
                        <td><a href="{% url "ingredient_update" ingredient.id %}">{{ ingredient.name }}</a></td>
                        <td>{{ ingredient.quantity }}</td>
                        <td>{{ ingredient.unit }}</td>
                        <td>{{ ingredient.unit_price }}</td>
                        <td><a href="{% url "ingredient_delete" ingredient.id %}">Delete</a></td>
                    </tr>
                {% endfor %}
                </tbody>
                <tfoot>
                <tr>
                    <td><a href="{% url "ingredient_create" %}">add</a></td>
                </tr>
                </tfoot>
            </table>
        </div>
    </div>
{% endblock %}

templates/inventory/ingredient_requirement.html
{% extends "inventory/base.html" %}
{% load static %}

{% block body %}
    <h3>Insufficient Ingredients</h3>
    <div class="d-flex align-items-center">
        <div class="border rounded">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Quantity Inventory</th>
                    <th scope="col">Quantity Requirement</th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody class="table-group-divider">
                {% for ingredient, recipe_requirement in requirement_ingredients %}
                    {% if recipe_requirement.quantity > ingredient.quantity %}
                        <tr>
                            <th scope="row" class="table-warning">{{ ingredient.id }}</th>
                            <td class="table-warning"><a
                                    href="{% url "ingredient_update" ingredient.id %}">{{ ingredient.name }}</a></td>
                            <td class="table-warning">{{ ingredient.quantity }}</td>
                            <td class="table-warning">{{ recipe_requirement.quantity }}</td>
                        </tr>
                    {% else %}
                        <tr>
                            <th scope="row">{{ ingredient.id }}</th>
                            <td><a href="{% url "ingredient_update" ingredient.id %}">{{ ingredient.name }}</a></td>
                            <td>{{ ingredient.quantity }}</td>
                            <td>{{ recipe_requirement.quantity }}</td>
                        </tr>
                    {% endif %}
                {% endfor %}
                </tbody>
                <tfoot>
                </tfoot>
            </table>
        </div>
    </div>
{% endblock %}

templates/inventory/menu_item.html
{% extends "inventory/base.html" %}
{% load static %}

{% block body %}
    <div class="d-flex align-items-center">
        <div class="border rounded">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Title</th>
                    <th scope="col">Price</th>
                    <th scope="col">Recipe</th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody class="table-group-divider">
                {% for menu_item in menuitem_list %}
                    <tr>
                        <th scope="row">1</th>
                        <td><a href="{% url "menu_item_update" menu_item.id %}">{{ menu_item.title }}</a></td>
                        <td>{{ menu_item.price }}</td>
                        <td><a href="{% url "recipe_requirement_list" menu_item.id %}">Recipe</a></td>
                        <td><a class="link-danger link-underline-opacity-0"
                               href="{% url "menu_item_delete" menu_item.id %}">Delete</a></td>
                    </tr>
                {% endfor %}
                </tbody>
                <tfoot>
                <tr>
                    <td><a href="{% url "menu_item_create" %}">add</a></td>
                </tr>
                </tfoot>
            </table>
        </div>
    </div>
{% endblock %}

templates/inventory/purchase.html
{% extends "inventory/base.html" %}
{% load static %}

{% block body %}
    <div class="d-flex align-items-center">
        <div class="border rounded">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">menu Item</th>
                    <th scope="col">Revenue</th>
                    <th scope="col">Cost</th>
                    <th scope="col">Profit</th>
                    <th scope="col">Time Stamp</th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody class="table-group-divider">
                {% for purchase in purchase_list %}
                    <tr>
                        <th scope="row">1</th>
                        <td>{{ purchase.menu_item }}</td>
                        <td>{{ purchase.revenue }}</td>
                        <td>{{ purchase.cost }}</td>
                        <td>{{ purchase.profit }}</td>
                        <td>{{ purchase.timestamp }}</td>
                        <td><a href="{% url "purchase_delete" purchase.id %}">Delete</a></td>
                    </tr>
                {% endfor %}
                </tbody>
                <tfoot>
                <tr>
                    <td><a href="{% url "purchase_create" %}">add</a></td>
                </tr>
                </tfoot>
            </table>
        </div>
    </div>
{% endblock %}

templates/inventory/recipe_requirement.html
{% extends "inventory/base.html" %}
{% load static %}

{% block body %}
    <div class="d-flex align-items-center">
        <div class="border rounded">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Ingredient</th>
                    <th scope="col">Quantity</th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody class="table-group-divider">
                {% for recipe_requirement in recipe_requirements %}
                    <tr>
                        <th scope="row">1</th>
                        <td>
                            <a href="{% url "recipe_requirement_update" menu.id recipe_requirement.id %}">{{ recipe_requirement.ingredient.name }}</a>
                        </td>
                        <td>{{ recipe_requirement.quantity }}</td>
                        <td><a class="link-danger link-underline-opacity-0"
                               href="{% url "recipe_requirement_delete" menu.id recipe_requirement.id %}">Delete</a></td>
                    </tr>
                {% endfor %}
                </tbody>
                <tfoot>
                <tr>
                    <td><a href="{% url 'recipe_requirement_create' menu.id %}">Add</a></td>
                </tr>
                </tfoot>
            </table>
        </div>
    </div>
{% endblock %}

templates/inventory/update_menu_item.html
{% extends "inventory/base.html" %}
{% load static %}

{% block body %}
    <div class="d-flex align-items-center">
        <div class="border rounded">
            <form class="row g-3 needs-validation" method="post">
                {% csrf_token %}
                <div class="col-md-6">
                    <label for="id_title" class="form-label">Name</label>
                    {{ form.title }}
                    <div class="valid-feedback">
                        Looks good!
                    </div>
                </div>
                <div class="col-md-6">
                    <label for="id_price" class="form-label">Quantity</label>
                    {{ form.price }}
                    <div class="valid-feedback">
                        Looks good!
                    </div>
                </div>
                <div class="col-12">
                    <input class="btn btn-primary" type="submit" value="Submit" />
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/inventory/update_recipe_requirement.html
{% extends "inventory/base.html" %}
{% load static %}

{% block body %}
    <h1> New Requirement for {{ menu_item.title }} recipe</h1>
    <div class="d-flex align-items-center">
        <div class="border rounded">
            <form class="row g-3 needs-validation" method="post">
                {% csrf_token %}
                <div class="col-md-6">
                    <label for="id_ingredient" class="form-label">Name</label>
                    {{ form.ingredient }}
                </div>
                <div class="col-md-6">
                    <label for="id_quantity" class="form-label">Quantity</label>
                    {{ form.quantity }}
                    <div class="valid-feedback">
                        Looks good!
                    </div>
                </div>
                <div class="col-12">
                    <input class="btn btn-primary" type="submit" value="Submit"/>
                </div>
            </form>
        </div>
    </div>
{% endblock %}